version: '3'

services:

# ==================================================
# VPN Containers
# ==================================================
    privoxyvpn: 
        image: binhex/arch-privoxyvpn:latest
        container_name: privoxyvpn
        cap_add:
            - net_admin
        volumes:
            - ${APPDATA_PATH}/prixoxyvpn:/config
            - /etc/localtime:/etc/localtime:ro 
        environment:
            - PUID=0 #${PUID}
            - PGID=0 #${PGID} # If PGID is set, it leaks the IP in qbittorrent
            - VPN_ENABLED=yes 
            - VPN_USER=${PRIVOXY_VPN_VPN_USER}
            - VPN_PASS=${PRIVOXY_VPN_VPN_PASS}
            - VPN_PROV=custom                   # Surfshark
            - STRICT_PORT_FORWARD=yes
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=${PRIVOXY_LAN_NETWORK}
            - NAME_SERVERS=1.1.1.1
            - DELUGE_DAEMON_LOG_LEVEL=info
            - DELUGE_WEB_LOG_LEVEL=info
            - DEBUG=false
            - UMASK=000
        ports:
            - 8118:8118         # PrivoxyVPN
            - 9118:9118         # Privoxyvpn
            - 8112:8112/tcp     # Deluge
            - 58846:58846/tcp   # Deluge
            - 58946:58946/tcp   # Deluge
            - 58946:58946/udp   # Deluge
            - 8088:8080         # Sabnzbd (usenet-compose.yml)
            - 9990:9090         # Sabnzbd (usenet-compose.yml)
            - 6789:6789         # Nzbget
            - 8008:8000         # Pyload
            - 7227:7227         # Pyload
            - 8989:8989         # Sonarr
            - 7878:7878         # Radarr
            - 7879:7879         # Radarr-4k
            - 6767:6767         # Bazarr
            - 9117:9117         # Jackett
            - 5076:5076         # Nzbhydra2
        network_mode: bridge
        restart: ${RESTART_POLICY}

# ==================================================
# Download Containers
# ==================================================
    deluge:
        image: linuxserver/deluge:latest
        container_name: deluge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
            #- DELUGE_LOGLEVEL=info #optional
        volumes:
            - ${APPDATA_PATH}/deluge:/config
            - ${DOWNLOADS_PATH}/deluge:/downloads
        #ports:
        #    - 58846:58846/tcp
        #    - 58946:58946/tcp
        #    - 58946:58946/udp
        #    - 8112:8112/tcp
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
        restart: ${RESTART_POLICY}
        
    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/sabnzbd:/config
            - ${DOWNLOADS_PATH}/sabnzbd:/downloads
#            - /path/to/incomplete/downloads:/incomplete-downloads #optional
        #ports:
        #    - 8080:8080
        #    - 9090:9090
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
        restart: ${RESTART_POLICY}
    
    nzbget:
        image: linuxserver/nzbget:latest
        container_name: nzbget
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/nzbget:/config
            - ${DOWNLOADS_PATH}/nzbget:/downloads
        #ports:
        #  - 6789:6789
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
        restart: ${RESTART_POLICY}

    pyload:
        image: linuxserver/pyload:latest
        container_name: pyload
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/pyload:/config
            - ${DOWNLOADS_PATH}/pyload:/downloads
        #ports:
            #- 8000:8000
            #- 7227:7227 #optional
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
        restart: ${RESTART_POLICY}
        
# ==================================================
# Media Management Containers
# ==================================================
    sonarr:
        image: linuxserver/sonarr:preview
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${APPDATA_PATH}/sonarr:/config
            - ${MEDIA_PATH}:/media
            - ${DOWNLOADS_PATH}:/downloads
        # Set on privoxy-vpn
        #ports:
        #    - 8989:8989     # Sonarr
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
            - deluge
            - jackett
        restart: ${RESTART_POLICY}

    radarr:
        image: linuxserver/radarr:nightly
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${APPDATA_PATH}/radarr:/config
            - ${MEDIA_PATH}:/media
            - ${DOWNLOADS_PATH}:/downloads
        # Set on privoxy-vpn
        #ports:
        #    - 7878:7878     # Radarr
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
            - deluge
            - jackett
        restart: ${RESTART_POLICY}
    
    radarr-4k:
        # NOTE: For this to work, you need to change Radarr config to be
        # on 7879
        image: linuxserver/radarr:nightly
        container_name: radarr-4k
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${APPDATA_PATH}/radarr-4k:/config
            - ${MEDIA_PATH}:/media
            - ${DOWNLOADS_PATH}:/downloads
        # Set on privoxy-vpn
        #ports:
        #    - 7879:7878     # Radarr-4k
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
            - deluge
            - jackett
        restart: ${RESTART_POLICY}

    bazarr:
        image: linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${APPDATA_PATH}/bazarr:/config
            - ${HOME_TANK_PATH}:/data
        #ports:
        #    - 6767:6767
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
            - sonarr
            - radarr
        restart: ${RESTART_POLICY}

# ==================================================
# Indexer Containers
# ==================================================
    jackett:
        image: linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/jackett:/config
            - ${DOWNLOADS_PATH}/deluge/watch:/downloads
        # ports:
        #   - 9117:9117
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
        restart: ${RESTART_POLICY}
    
    nzbhydra2:
        image: linuxserver/nzbhydra2:latest
        container_name: nzbhydra2
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/nzbhydra2:/config
            - ${DOWNLOADS_PATH}/nzbhydra2:/downloads
        #ports:
        #    - 5076:5076
        network_mode: "service:privoxyvpn"
        depends_on:
            - privoxyvpn
        restart: ${RESTART_POLICY}

# ==================================================
# Monitoring Containers (no VPN, bridge network)
# ==================================================
    tautulli:
        image: linuxserver/tautulli:latest
        container_name: tautulli
        depends_on:
            - plex
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/tautulli:/config
            - ${APPDATA_PATH}/plex/Plex\ Media\ Server/Logs:/logs
        ports:
            - 8181:8181
        network_mode: bridge
        restart: ${RESTART_POLICY}

# ==================================================
# Plex and Plex Users Management (no VPN, host and bridge networks)
# ==================================================
    plex:
        image: linuxserver/plex:latest
        container_name: plex
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VERSION=docker
            - UMASK_SET=022 #optional
            - PLEX_CLAIM= #optional
        volumes:
            - ${APPDATA_PATH}/plex:/config
            - ${MEDIA_PATH}:/media
        network_mode: host
        restart: ${RESTART_POLICY}
    
    ombi:
        image: linuxserver/ombi:latest
        container_name: ombi
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - BASE_URL=/ombi #optional
        volumes:
            - ${APPDATA_PATH}/ombi:/config
        ports:
            - 3579:3579
        network_mode: bridge
        restart: ${RESTART_POLICY}
