version: '3'

services:
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    environment:
      - TZ=${TZ}
      - APP_KEY=${FIREFLY_FIREFLY_APP_KEY}
      - DB_HOST=${FIREFLY_FIREFLY_DB_HOST}
      - DB_PORT=${FIREFLY_FIREFLY_DB_PORT}
      - DB_CONNECTION=mysql
      - DB_DATABASE=${FIREFLY_FIREFLY_DB_NAME}
      - DB_USERNAME=${FIREFLY_FIREFLY_DB_USERNAME}
      - DB_PASSWORD=${FIREFLY_FIREFLY_DB_PASSWORD}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis-firefly
      - REDIS_PORT=6379
      - APP_URL=${FIREFLY_FIREFLY_APP_URL}
      - TRUSTED_PROXIES=**
      - MAIL_MAILER=${FIREFLY_FIREFLY_MAIL_MAILER}
      - MAIL_HOST=${FIREFLY_FIREFLY_MAIL_HOST}
      - MAIL_PORT=${FIREFLY_FIREFLY_MAIL_PORT}
      - MAIL_FROM=${FIREFLY_FIREFLY_MAIL_FROM}
      - MAIL_USERNAME=${FIREFLY_FIREFLY_MAIL_USERNAME}
      - MAIL_PASSWORD=${FIREFLY_FIREFLY_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${FIREFLY_FIREFLY_MAIL_ENCRYPTION}
    volumes:
      - ${APPDATA_PATH}/firefly:/var/www/html/storage/upload
    ports:
    # You may disable ports if they are forwarded by reverse proxy
      - 8666:8080
    networks:
      - firefly
      - reverse-proxy
    depends_on:
      - mariadb-firefly
    restart: ${RESTART_POLICY}

  redis-firefly:
    image: redis:latest
    container_name: redis-firefly
    environment:
      - TZ=${TZ}
    networks:
      - firefly
    depends_on:
      - firefly
    restart: ${RESTART_POLICY}

  firefly-cron:
    image: alpine:latest
    container_name: firefly-cron
    volumes:
      - ${APPDATA_PATH}/firefly-cron:/firefly-cron
      - /etc/localtime:/etc/localtime:ro
    networks:
      - firefly
    depends_on:
      - firefly
    command: sh -c " echo \"15 0 * * * wget http://firefly:8080/api/v1/cron/${FIREFLY_FIREFLY_CRON_TOKEN} >> /firefly-cron/firefly-cron.log 2>&1\" | crontab - && crond -f -L /dev/stdout"

  mariadb-firefly:
    image: linuxserver/mariadb:latest
    container_name: mariadb-firefly
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${FIREFLY_MARIADB_FIREFLY_ROOT_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/mariadb-firefly:/config
    #ports:
    #  - 3306:3306
    networks:
      - firefly
    restart: ${RESTART_POLICY}

networks:
  firefly:
    name: firefly
    driver: bridge

  reverse-proxy:
    external:
      name: reverse-proxy
