version: '3'

services:

# ==================================================
# Watchtower
# ==================================================
    # watchtower:
    #     image: containrrr/watchtower:latest
    #     container_name: watchtower
    #     environment:
    #         - WATCHTOWER_CLEANUP=true
    #         - WATCHTOWER_INCLUDE_STOPPED=true
    #         - WATCHTOWER_REVIVE_STOPPED=true
    #         - WATCHTOWER_DEBUG=true
    #         - WATCHTOWER_SCHEDULE=${STANDALONE_WATCHTOWER_SCHEDULE}   # Everyday at 1am
    #         #- WATCHTOWER_ROLLING_RESTART=true
    #         - WATCHTOWER_TIMEOUT=60
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     network_mode: bridge
    #     restart: ${RESTART_POLICY}

# ==================================================
# ddclient
# ==================================================
    ddclient:
        image: linuxserver/ddclient:latest
        container_name: ddclient
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/ddclient:/config
        network_mode: bridge
        restart: ${RESTART_POLICY}

# ==================================================
# Duplicati
# ==================================================
    # duplicati:
    #     image: linuxserver/duplicati:latest
    #     container_name: duplicati
    #     hostname: duplicati
    #     environment:
    #         - PUID=${PUID}
    #         - PGID=${PGID}
    #         - TZ=${TZ}
    #     volumes:
    #         - ${APPDATA_PATH}/duplicati:/config
    #         - ${APPDATA_PATH}:/backups
    #         - ${APPDATA_PATH}:/source:ro
    #     ports:
    #         - 8200:8200
    #     network_mode: bridge
    #     restart: ${RESTART_POLICY}
