version: '3'

services:

# ==================================================
# Watchtower
# ==================================================
    # watchtower:
    #     image: containrrr/watchtower:latest
    #     container_name: watchtower
    #     environment:
    #         - WATCHTOWER_CLEANUP=true
    #         - WATCHTOWER_INCLUDE_STOPPED=true
    #         - WATCHTOWER_REVIVE_STOPPED=true
    #         - WATCHTOWER_DEBUG=true
    #         - WATCHTOWER_SCHEDULE=0 0 1 * * ?   # Everyday at 1am
    #         #- WATCHTOWER_ROLLING_RESTART=true
    #         - WATCHTOWER_TIMEOUT=60  
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     network_mode: bridge
    #     restart: ${RESTART_POLICY}

# ==================================================
# Swag (former letsencrypt)
# ==================================================
    swag:
        image: linuxserver/swag:latest
        container_name: swag
        cap_add:
            - net_admin
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - URL=${STANDALONE_SWAG_URL}
            - SUBDOMAINS=${STANDALONE_SWAG_SUBDOMAINS}
            - VALIDATION=${STANDALONE_SWAG_VALIDATION}
            - DNSPLUGIN=${STANDALONE_SWAG_DNSPLUGIN}
            - DHLEVEL=2048
            - ONLY_SUBDOMAINS=${STANDALONE_SWAG_ONLYSUBDOMAINS}
        volumes:
            - ${APPDATA_PATH}/swag:/config
        ports:
            - 80:80
            - 443:443
        network_mode: bridge
        restart: ${RESTART_POLICY}

# ==================================================
# ddclient
# ==================================================
    ddclient:
        image: linuxserver/ddclient:latest
        container_name: ddclient
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${APPDATA_PATH}/ddclient:/config
        network_mode: bridge
        restart: ${RESTART_POLICY}

# ==================================================
# Duplicati
# ==================================================
    # duplicati:
    #     image: linuxserver/duplicati:latest
    #     container_name: duplicati
    #     hostname: duplicati
    #     environment:
    #         - PUID=${PUID}
    #         - PGID=${PGID}
    #         - TZ=${TZ}
    #     volumes:
    #         - ${APPDATA_PATH}/duplicati:/config
    #         - ${APPDATA_PATH}:/backups
    #         - ${APPDATA_PATH}:/source:ro
    #     ports:
    #         - 8200:8200
    #     network_mode: bridge
    #     restart: ${RESTART_POLICY}
